---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
dictionaryDefinitions:
  - name: cspell-words
    path: ./cspell-words.txt
    addWords: true
dictionaries:
  - cspell-words
ignorePaths:
  - .clang-format
  - .gitignore
  - Cargo.lock
  - Cargo.toml
  - build
  - cspell-words.txt
  - debug
  - gradle
  - gradlew
  - gradlew.bat
  - node_modules
  - package.json
  - packages/examples/**/*.json
  - pnpm-lock.yaml
  - pyproject.toml
  - requirements-dev.lock
  - requirements.lock
  - target
  - temp

...
