---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
dictionaryDefinitions:
  - name: cspell-words
    path: ./cspell-words.txt
    addWords: true
dictionaries:
  - cspell-words
ignorePaths:
  - node_modules
  - .gitignore
  - ./cspell-words.txt
  - ./pnpm-lock.yaml
