---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
dictionaryDefinitions:
  - name: cspell-words
    path: ./cspell-words.txt
    addWords: true
dictionaries:
  - cspell-words
ignorePaths:
  - .gitignore
  - build
  - cspell-words.txt
  - gradle
  - gradlew
  - gradlew.bat
  - node_modules
  - packages/examples/**/*.json
  - pnpm-lock.yaml
  - temp
